name: Publish WebApp

on:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
      WorkflowRunId:
        required: true
        type: string
  
jobs:
  publish_sample_site:
    name: Publish sample site
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ inputs.WorkflowRunId }}
    
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
         # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
           files: 'Sample.AspNetCore/appsettings.json'
        env:
          Urls.TermsOfServiceUrl: ${{ secrets.SWEDEN_MERCHANT_ID }}
          Urls.CallBackUrl: ${{ secrets.SWEDEN_MERCHANT_SECRET }}
          Urls.CancelUrl: ${{ secrets.NORWAY_MERCHANT_ID }}
          Urls.CompleteUrl: ${{ secrets.NORWAY_MERCHANT_SECRET }}
          Urls.PaymentUrl: ${{ secrets.FINNISH_MERCHANT_ID }}
          LogoUrl: ${{ secrets.FINNISH_MERCHANT_SECRET }}
          HostUrls.0: https://svea-webpay-sdk-001-${{ inputs.Environment }}.azurewebsites.net/api/svea/push/{checkout.order.uri}/?marketId={marketId}
          StandardCheckoutPaymentUrl: https://svea-webpay-sdk-001-${{ inputs.Environment }}.azurewebsites.net/terms
          AnonymousCheckoutPaymentUrl: https://svea-webpay-sdk-001-${{ inputs.Environment }}.azurewebsites.net/CheckOut/LoadPaymentMenu
          PaymentMenuPaymentUrl: https://svea-webpay-sdk-001-${{ inputs.Environment }}.azurewebsites.net/checkout/thankyou
      
      # - name: 'Run Azure webapp deploy using publish profile credentials'
      #   uses: azure/webapps-deploy@v2
      #   with: 
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }} # Define secret variable in repository settings as per action documentation
      #     package: 'Sample.AspNetCore'